#ansible -i hosts.ini all -m ping

- name: Team1
  hosts: team1
  # gather_facts: false
  become: yes
  roles:
    - role: create_team
    # - role: geerlingguy.apache
      # # team_username: "{{ team_username }}"
      # editor: "vim"



- name: Team2
  hosts: team2
  # gather_facts: false
  become: yes

  roles:
    - role: create_team
      # # team_username: "{{ team_username }}"
      # editor: "nano"

