---
#Ok -- no changes reqiuired on remote node
#Changed -- when ansible playbook state is not synched with remote node
#Failed  -- ansible tried to change the state but failed to apply

- name: nginx server
  become: true
  hosts: all
  roles:
    - role: create_team
