---
- name: HTTP server
  become: true
  hosts: node1
  tasks:
    - name: uninstall apache HTTP server
      apt: name=nginx state=absent
    - name: stop HTTP server
      service: name=nginx enabled=no state=stopped
- name: tree
  become: true
  hosts: node2
  tasks:
    - name: uninstall tree
      apt: name=tree state=absent
