- name: install editor
  apt:
    name: "{{ editor }}"
  
- name: create user 
  ansible.builtin.user:
    name: "{{ team_username }}"
    comment: Created by ansible
    group: sudo

- name: create foo.log
  ansible.builtin.file:
    path: /var/log/foo.log
    state: touch
- name: copy applicaiton properties
  copy:
    src: files/application.properties
    dest: /tmp/application.properties
  notify:
    - cleanup log files